### ISSUE TITLE
Ghost mode

### ISSUE THREAD

**Issue by Adryd** [CCBlueX/LiquidBounce-1.13-Issues#6]
A way to hide the prominent GUI elements

**Comment by Marco-MC** [comment]
Please open issues like that in the 1.8.9 Issues Repository.
The 1.8.9 is the main version of LiquidBounce, the other versions just ports (with extra features they got requeted etc).

Also, I don't want to add a ghost mode. (https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1147 etc)
